#!/usr/bin/env python3
"""
Generates the MDS AppTech particle-ring mark.

The ring is a cloud of dots orbiting an empty centre, which is where the
wordmark sits. Everything is deterministic - the seed is fixed - so a re-run
reproduces the same mark rather than a new random one, and the SVG can be
regenerated after a colour change without the logo shifting.

Run: python3 tools/make-logo.py
"""
import math
import random

VIEW = 100.0
CENTRE = VIEW / 2

def ring(seed, count, r_mean, r_spread, dot_min, dot_max):
    """Dots scattered around a circle, denser and fatter at the band centre."""
    rng = random.Random(seed)
    out = []
    for i in range(count):
        # Jittered angle off an even spacing: keeps the ring from clumping
        # the way pure uniform sampling does, while still looking organic.
        angle = (i / count) * math.tau + rng.gauss(0, math.tau / (count * 1.6))
        # Gaussian radius so density falls off either side of the band.
        radius = rng.gauss(r_mean, r_spread)
        if not (r_mean - r_spread * 2.6 < radius < r_mean + r_spread * 2.6):
            continue
        # Dots near the band centre are the largest and most opaque; the
        # strays further out fade, which is what gives the ring its depth.
        closeness = 1 - min(abs(radius - r_mean) / (r_spread * 2.6), 1)
        size = dot_min + (dot_max - dot_min) * (closeness ** 1.5) * rng.uniform(0.55, 1.0)
        opacity = 0.30 + 0.70 * (closeness ** 1.2) * rng.uniform(0.7, 1.0)
        x = CENTRE + math.cos(angle) * radius
        y = CENTRE + math.sin(angle) * radius
        out.append((x, y, size, opacity))
    return out

def dots_svg(dots, indent="    "):
    return "\n".join(
        f'{indent}<circle cx="{x:.2f}" cy="{y:.2f}" r="{s:.2f}" opacity="{o:.2f}"/>'
        for x, y, s, o in dots
    )

# Detailed: hero, app icon, OG image. Reads as a particle sphere at 100px+.
DETAILED = ring(seed=7, count=340, r_mean=37.5, r_spread=3.4, dot_min=0.30, dot_max=1.55)
# Compact: header and favicon. Fewer, fatter dots survive being drawn at 32px.
COMPACT = ring(seed=7, count=88, r_mean=37.0, r_spread=2.4, dot_min=0.95, dot_max=2.60)

if __name__ == "__main__":
    import pathlib

    root = pathlib.Path(__file__).resolve().parent.parent

    # 1. The dot geometry the Astro component imports.
    (root / "src/components/logo-dots.ts").write_text(
        "// Generated by tools/make-logo.py - do not edit by hand.\n"
        "// Re-run the script after changing the ring parameters.\n\n"
        f"export const DETAILED_DOTS = `\n{dots_svg(DETAILED)}\n`;\n\n"
        f"export const COMPACT_DOTS = `\n{dots_svg(COMPACT)}\n`;\n"
    )

    # 2. The standalone assets. Each carries its own copy of the gradient,
    #    since a favicon or an OG card has no page CSS to inherit from.
    grad = (
        '    <linearGradient id="brandGradient" gradientUnits="userSpaceOnUse"'
        ' x1="8" y1="4" x2="92" y2="96">\n'
        '      <stop offset="0%" stop-color="#5549E8"/>\n'
        '      <stop offset="50%" stop-color="#3475DF"/>\n'
        '      <stop offset="100%" stop-color="#18B8D2"/>\n'
        '    </linearGradient>'
    )
    font = "Inter, Helvetica Neue, Helvetica, Arial, sans-serif"

    # Favicon: on a gradient tile, because a transparent mark disappears
    # against a dark browser tab bar.
    (root / "public/favicon.svg").write_text(
        f'<svg width="32" height="32" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n'
        f'  <defs>\n{grad}\n  </defs>\n'
        f'  <rect width="100" height="100" rx="24" fill="url(#brandGradient)"/>\n'
        f'  <g fill="#ffffff">\n{dots_svg(COMPACT)}\n  </g>\n'
        f'  <text x="50" y="50" text-anchor="middle" dominant-baseline="central"'
        f' font-family="{font}" font-size="21" font-weight="700" fill="#ffffff">M</text>\n'
        f'</svg>\n'
    )

    # Apple touch icon: iOS applies its own corner mask, so no rounding here.
    (root / "public/apple-touch-icon.svg").write_text(
        f'<svg width="180" height="180" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n'
        f'  <defs>\n{grad}\n  </defs>\n'
        f'  <rect width="100" height="100" fill="url(#brandGradient)"/>\n'
        f'  <g fill="#ffffff">\n{dots_svg(DETAILED)}\n  </g>\n'
        f'  <text x="50" y="50" text-anchor="middle" dominant-baseline="central"'
        f' font-family="{font}" font-size="17" font-weight="700" letter-spacing="1.5"'
        f' fill="#ffffff">MDS</text>\n'
        f'</svg>\n'
    )

    # Open Graph card. The rule spans the full width, so it needs a second
    # gradient in the outer coordinate space.
    rule = (
        '    <linearGradient id="ruleGradient" gradientUnits="userSpaceOnUse"'
        ' x1="96" y1="0" x2="1104" y2="0">\n'
        '      <stop offset="0%" stop-color="#5549E8"/>\n'
        '      <stop offset="50%" stop-color="#3475DF"/>\n'
        '      <stop offset="100%" stop-color="#18B8D2"/>\n'
        '    </linearGradient>'
    )
    (root / "public/og-image.svg").write_text(
        f'<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">\n'
        f'  <defs>\n{grad}\n{rule}\n  </defs>\n'
        f'  <rect width="1200" height="630" fill="#ffffff"/>\n'
        f'  <g transform="translate(96,150) scale(3.3)">\n'
        f'    <g fill="url(#brandGradient)">\n{dots_svg(DETAILED, indent="      ")}\n    </g>\n'
        f'    <text x="50" y="50" text-anchor="middle" dominant-baseline="central"'
        f' font-family="{font}" font-size="17" font-weight="700" letter-spacing="1.5"'
        f' fill="#171717">MDS</text>\n'
        f'  </g>\n'
        f'  <text x="500" y="270" font-family="{font}" font-size="64" font-weight="700"'
        f' fill="#171717">MDS AppTech</text>\n'
        f'  <text x="500" y="325" font-family="{font}" font-size="28"'
        f' fill="#525252">Mobile Apps &amp; Web Pages</text>\n'
        f'  <text x="500" y="400" font-family="{font}" font-size="22"'
        f' fill="#737373">A small studio. Apps built properly.</text>\n'
        f'  <rect x="96" y="512" width="1008" height="4" rx="2" fill="url(#ruleGradient)" opacity="0.4"/>\n'
        f'  <text x="96" y="566" font-family="{font}" font-size="20" font-weight="500"'
        f' fill="#525252">mdsapptech.com</text>\n'
        f'</svg>\n'
    )

    print(f"detailed: {len(DETAILED)} dots    compact: {len(COMPACT)} dots")
    print("wrote src/components/logo-dots.ts, public/favicon.svg,")
    print("      public/apple-touch-icon.svg, public/og-image.svg")
    print()
    print("The PNG fallbacks are rendered separately (macOS):")
    print("  qlmanage -t -s 180 -o /tmp public/apple-touch-icon.svg")
    print("  sips -s format png /tmp/apple-touch-icon.svg.png --out public/apple-touch-icon.png")
